### ISSUE TITLE
New CLI Docs

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#1]
- [x] Migrate the new [Gatsby site](https://github.com/tanyabrassie/npm-cli/) into `@npm/cli/docs/`
- [x] Clean up styles & the overall template's code
- [x] Copy existing cli docs into the new format
- [x] Remove irrelevant documentation (ie. anything that is not cli-specific)
