### ISSUE TITLE
Update & sync repository labels

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#109]
### Problem Space
Syncing labels across multiple projects is hard

### Solution
- Creat a GitHub Action/Automation to sync these labels

### Exit Criteria
- [ ] Check daily for what labels exist on our defined set of maintained repos
- [ ] Save back to a file inside `./data` (ex. `./data/labels.json`) a deduped copy of these labels (similar to `./data/latest.json`) 
  - note: we do not need historical references... just latest
- [ ] Add/update the labels across the defined set of maintained repos
