### ISSUE TITLE
Release npm `v6.13.0`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#12]
- [x] Land [`funding` / `npm fund` work](https://github.com/npm/statusboard/issues/2)
- [x] Land `npm team rm <org>:developers` work (not yet staged)
- [x] Land [279](https://github.com/npm/cli/pull/279)

**Comment by ruyadorno** [comment]
I guess the other issues here will have to be carried on to next release

**Comment by darcyclarke** [comment]
@ruyadorno yep, I'm carrying them over so we can properly close this `Epic` out
