### ISSUE TITLE
Create npm.community Landing Page

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#13]
- [x] Design/developer mock page
- [x] Determine deployment/hosting/domain
- [x] Work with marketing on messaging & what links to use
- [x] Queue up for launch on Tuesday, November 5th
