### ISSUE TITLE
Fix up & improve statusboard

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#14]
- [x] Set up a better development environment/workflow
- [x] Recursively follow paginated responses (currently we're not grabbing all repositories)
- [x] Add secondary metrics (ex. specific labels/count)
- [x] Store data snapshots
- [x] Allow for searching/filtering of projects by column value
- [x] Clean up styles/formatting
- [x] Add test coverage to columns
- [x] Set up GitHub actions to run fetches & builds
