### ISSUE TITLE
Migrate & archive npm.community

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#15]
When we re-open the `cli/issues` on Tuesday, November 5th, we'd like to automatically generate tickets referencing any remaining [#bug threads](https://npm.community/c/bugs).

- [x] Backup forums (`.sql` has been saved to Dropbox as of Sunday Nov 3rd)
- [x] **Nov 5th:** Set the forums to read-only mode
- [x] **Nov 5th:** Run Discourse query to capture all open #bug tickets
- [x] **Nov 5th:** Run GitHub query to generate issues against the `cli` referencing their archived counterparts discussions & labeling where possible/appropriate
- [x] **Nov 5th:** Add pinned topic to each Discourse forum pointing to the announcement blog post & where to find support
