### ISSUE TITLE
Remove gatsby & update help docs

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#198]
- [ ] Remove gatsby site
- [ ] Remove build steps to produce gatsby site
- [ ] Update `npm help` to support a new `--browser` implementation
