### ISSUE TITLE
Add `funding` to package.json

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#2]
- [x] Implement `npm i` "nag" at the end of output
	ex. `23 packages are looking for funding. Run "npm fund" to find out more.`
- [x] Implement `--no-fund` flag to opt-out of the "nag" when installing
- [x] Implement `npm fund` subcommand which lists out all the funding references
- [x] Write tests for the "nag", `--no-fund` & the `npm fund` subcommand
- [x] Document the subcommand functionality
- [x] Document the schema change of `package.json` ([can use/reference this spec once updated](https://gist.github.com/darcyclarke/dd77c8f1fb895c5063bf39723a27d0fa))
- [x] Add a visual representation for the `funding` field/value on package pages
- ~Add `funding` to Pakument/Corgi objects: https://github.com/npm/validate-and-store~ it looks like we don't really need it, the reference implementation at [npm repo](https://github.com/npm/cli/blob/latest/lib/repo.js#L18) is actually using the full metadata in which makes sense since we don't want to tax the entire registry just for users that are manually running the `npm fund <package>` command.
