### ISSUE TITLE
New Docs Website

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#21]
- [x] Create a build pipeline/process, separate from the cli builds, to generate the docs site (use GitHub actions if possible)
- [x] Add persistent toggle options for sub navs (ie. closed/opened states persist page reloads)
- [x] File a ticket with SRE team to create a subdomain (ex. `preview.npmjs.com`)
- [x] Work with SRE team to determine proper origin
- [x] Talk with Ahmad about the future of the `support.npmjs.com` Zendesk help portal (ask about timelines/release schedule)
