### ISSUE TITLE
[Web] Add Package Exploration to Website

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#22]
- [x] Work with @darcyclarke to create package exploration tab
- [x] Fork &/or pull the components out for the file directory/explorer from [**unpkg**](https://github.com/mjackson/unpkg) and/or [react keyed](https://github.com/uptick/react-keyed-file-browser)
- [x] Add beta logo
- [x] Add org-only conditional
- [x] Add no-file-explore page content
- [x] Add tests
- [x] Security validation with security team
