### ISSUE TITLE
Archive legacy projects

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#26]
- [x] Identify criteria for legacy projects (ex. anything that hasn't been touched in 2 years)
- [x] Query for projects meeting the criteria
- [x] Queue up engineering org about intent
- [x] Give grace period
- [x] Archive projects

```
[
  "https://github.com/npm/npm-lylog",
  "https://github.com/npm/package-audit",
  "https://github.com/npm/redsess",
  "https://github.com/npm/fastly-audit-purge",
  "https://github.com/npm/node-github-url-from-git",
  "https://github.com/npm/npm-fastly-purge",
  "https://github.com/npm/ansible-bashpocalypse",
  "https://github.com/npm/npm_conf",
  "https://github.com/npm/ec2tail",
  "https://github.com/npm/npm-skim-registry",
  "https://github.com/npm/npm-tutor",
  "https://github.com/npm/npm-registry-readme-trim",
  "https://github.com/npm/registry-cert-verification",
  "https://github.com/npm/npm-collection-staff-picks",
  "https://github.com/npm/lylog",
  "https://github.com/npm/normalize-license-data",
  "https://github.com/npm/rderby",
  "https://github.com/npm/shirts",
  "https://github.com/npm/git-repo-manager",
  "https://github.com/npm/css",
  "https://github.com/npm/npm-logbot",
  "https://github.com/npm/callback-tracker",
  "https://github.com/npm/couch-readonly-replica",
  "https://github.com/npm/keyword-context",
  "https://github.com/npm/npm-fullfat-registry",
  "https://github.com/npm/pingme",
  "https://github.com/npm/graphics",
  "https://github.com/npm/create-test-package",
  "https://github.com/npm/npme-trusty",
  "https://github.com/npm/npme-unknown",
  "https://github.com/npm/site-structure",
  "https://github.com/npm/oss-license-name-to-url",
  "https://github.com/npm/ansible-ftools",
  "https://github.com/npm/npme-centos65",
  "https://github.com/npm/readdir-scoped-modules",
  "https://github.com/npm/npme-ansible-module",
  "https://github.com/npm/Paquetes-de-Codigo-Abierto",
  "https://github.com/npm/uid-number",
  "https://github.com/npm/npmo-auth-ldap",
  "https://github.com/npm/scope-it",
  "https://github.com/npm/numbat-analyzer",
  "https://github.com/npm/npm-marketing-changes-feed",
  "https://github.com/npm/Paquetes-de-Codigo-Abierto",
  "https://github.com/npm/npmconf",
  "https://github.com/npm/newww-tests",
  "https://github.com/npm/talk-proposals",
  "https://github.com/npm/oss-weekly",
  "https://github.com/npm/npm-marketing-sidebar-blob",
  "https://github.com/npm/blankie",
  "https://github.com/npm/eloqua-client",
  "https://github.com/npm/divot",
  "https://github.com/npm/npmo-auth-sso",
  "https://github.com/npm/tarball-url-info",
  "https://github.com/npm/token-facilitator",
  "https://github.com/npm/node-oauth2-server",
  "https://github.com/npm/express-oauth-server",
  "https://github.com/npm/handlebars-helper-from-package",
  "https://github.com/npm/npm-tips",
  "https://github.com/npm/normalize-registry-metadata",
  "https://github.com/npm/realize-package-specifier",
  "https://github.com/npm/new-docs",
  "https://github.com/npm/private-pkgs-orgs-docs",
  "https://github.com/npm/publishing-pkgs-docs",
  "https://github.com/npm/npme-auth-bitbucket",
  "https://github.com/npm/installation-setup-docs",
  "https://github.com/npm/fstream-ignore",
  "https://github.com/npm/registry-docs",
  "https://github.com/npm/ansible-pg-failover-config",
  "https://github.com/npm/npmo-auth-token",
  "https://github.com/npm/ifttt-hook-translator",
  "https://github.com/npm/sign-payload",
  "https://github.com/npm/marky-markdown-integration-test",
  "https://github.com/npm/how-npm-works-docs",
  "https://github.com/npm/readme-tester",
  "https://github.com/npm/ansible-role-deploy-update-code-git",
  "https://github.com/npm/captain-hook",
  "https://github.com/npm/tumblr-theme",
  "https://github.com/npm/support-cli",
  "https://github.com/npm/external-fetch",
  "https://github.com/npm/redis",
  "https://github.com/npm/npm-camp",
  "https://github.com/npm/nicely-placed-modification-logs",
  "https://github.com/npm/ansible-pg-failover",
  "https://github.com/npm/handlebars-helper-icon",
  "https://github.com/npm/npm-explicit-installs",
  "https://github.com/npm/npmo-docker-compose",
  "https://github.com/npm/npme-vagrant",
  "https://github.com/npm/couch-login",
  "https://github.com/npm/using-pkgs-docs",
  "https://github.com/npm/dr-frankenstyle",
  "https://github.com/npm/npm-like-im-5",
  "https://github.com/npm/public-api",
  "https://github.com/npm/dyn-js",
  "https://github.com/npm/route66",
  "https://github.com/npm/kenny-logins",
  "https://github.com/npm/ansible-percona",
  "https://github.com/npm/pkgize",
  "https://github.com/npm/marky-compare",
  "https://github.com/npm/handlebars-react",
  "https://github.com/npm/next.js",
  "https://github.com/npm/postgresql",
  "https://github.com/npm/background-refresh-cache",
  "https://github.com/npm/npme-auth-oauth2",
  "https://github.com/npm/annotation-api",
  "https://github.com/npm/annotation-poller",
  "https://github.com/npm/ansible-influxdb",
  "https://github.com/npm/ansible-role-elasticsearch",
  "https://github.com/npm/decorate",
  "https://github.com/npm/forza",
  "https://github.com/npm/fstream-npm",
  "https://github.com/npm/google-container-engine",
  "https://github.com/npm/hapi-stateless-notifications",
  "https://github.com/npm/humans",
  "https://github.com/npm/multi-fs",
  "https://github.com/npm/nm",
  "https://github.com/npm/npm-authify",
  "https://github.com/npm/npm-docker-couchdb",
  "https://github.com/npm/npm-hook-receiver",
  "https://github.com/npm/npme-auth-github",
  "https://github.com/npm/npme-auth-oauth2-restricted",
  "https://github.com/npm/npme-installer",
  "https://github.com/npm/npmi-cli",
  "https://github.com/npm/nsqjs",
  "https://github.com/npm/oauth2-server-pg",
  "https://github.com/npm/pivotal-ui",
  "https://github.com/npm/read",
  "https://github.com/npm/redis-pool",
  "https://github.com/npm/rust-readme-client",
  "https://github.com/npm/security-holder",
  "https://github.com/npm/seq-file",
  "https://github.com/npm/spife-dev-logger",
  "https://github.com/npm/tarpit",
  "https://github.com/npm/team-info-cache",
  "https://github.com/npm/weallcontribute",
  "https://github.com/npm/with-fixtures"
]
```
