### ISSUE TITLE
Update benchmark suite for v7

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#262]
- [ ] update/refactor our [benchmarks](https://github.com/npm/benchmarks) repo
  - [ ] ensure [`npm install` suite](https://github.com/npm/cli/pull/2212#issuecomment-731344591) runs properly against v7 releases
  - [ ] add new test fixtures based on [user feedback](https://github.com/npm/cli/issues/2011)
- [ ] respond to [user feedback](https://github.com/npm/cli/issues/2011)
- [ ] update **pnpm**'s [package manager benchmarks suite](https://github.com/pnpm/benchmarks-of-javascript-package-managers) to include v7
