### ISSUE TITLE
feat(workspaces): throw warning /w messaging for `unsupported` commands

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#269]
### Problem statement

Not all of `npm`'s commands make sense to be workspace-aware.

### Exit criteria 

* [x] All of the following commands should warn & display an unsupported message when workspace options are passed
* [x] Tests are written validating this behavior
* [x] Documentation is updated to identify these commands as not supporting `-w` / workspaces

**Unsupported commands:**
* [x] `adduser|login`
* [x] `bin`
* [x] `birthday`
* [x] `cache`
* [x] `completion`
* [x] `config|get|set`
* [x] `deprecate`
* [x] `doctor`
* [x] `edit`
* [x] `explore`
* [x] `help`
* [x] `help-search`
* [x] `hook`
* [x] `logout`
* [x] `org`
* [x] `owner`
* [x] `ping`
* [x] `prefix`
* [x] `profile`
* [x] `search`
* [x] `shrinkwrap`
* [x] `star`
* [x] `team`
* [x] `token`
* [x] `unstar`
* [x] `whoami`
