### ISSUE TITLE
Benchmarks work v2

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#27]
- [x] Remove/delete fork of **pnpm** benchmarks project
- [x] Update pull-request comment with threshold (use algorithm)
- [x] Make benchmark repo public (fixes auth issue https://github.com/npm/cli/blob/latest/.github/workflows/benchmark.yml#L38)

**Comment by mikemimik** [comment]
Archived Old Repository:
https://github.com/npm/package-manager-benchmarks

**Comment by mikemimik** [comment]
Second task completed by this pull-request https://github.com/npm/benchmarks/pull/4

**Comment by mikemimik** [comment]
Third task is contentious based on this https://github.com/npm/benchmarks/issues/3#issuecomment-562512422
