### ISSUE TITLE
feat(workspaces): support `context-aware` commands

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#270]
### Problem statement

These `npm` commands need to understand where they are to function & read from `package.json`; In the workspace setting, their implementation should be the equivalent of `cd <workspace-name> && npm <cmd>`.

### Exit criteria 

* [x] All of the following commands will be able to be run with `npm <cmd> -ws|-w`
* [x] Tests are written validating this behavior
* [x] Documentation is updated to identify these commands as unsupported by `npm -ws|-w` 

**`context-aware` commands:**
* [x] `docs`
* [x] `diff`
* [x] `dist-tag`
* [x] `pack`
* [x] `publish`
* [x] `repo`
* [x] `set-script`
* [x] `unpublish`
* [x] `version`
* [x] `view`
