### ISSUE TITLE
feat(workspaces): support `custom-read` commands

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#271]
### Problem statement

These `npm` commands need to understand where they are to function, read from `package.json` & require **custom** logic that **reads** with the installed tree.

### Exit criteria 

* [x] All of the following commands will be able to be run with `npm ws <cmd>`
* [x] Tests are written validating this behavior
* [x] Documentation is updated to identify these command's modified operation when run with `npm ws` 

**`custom-read` commands**

* [x] `audit`
* [x] `explain`
* [x] `fund`
* [x] `ls`
* [x] `outdated`
