### ISSUE TITLE
feat(workspaces): support `custom-read-write` commands

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#272]
### Problem statement

These `npm` commands need to understand where they are to function, read from `package.json` & require **custom** logic that can both **read & write** from the installed tree.

### Exit criteria 

* [x] All of the following commands will be able to be run with `npm ws <cmd>`
* [x] Tests are written validating this behavior
* [x] Documentation is updated to identify these command's modified operation when run with `npm ws` 

**`custom-read-write` commands**

* [x] `ci`
* [x] `dedupe`
* [x] `find-dupes`
* [x] `install-ci-test`
* [x] `install-test`
* [x] `install`
* [x] `link`
* [x] `rebuild`
* [x] `update`
* [x] `uninstall`
