### ISSUE TITLE
feat(arborist): add the ability to filter/scope by nodes

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#273]
### Problem statement

Adding the ability for [`Arborist`](https://github.com/npm/arborist/) to filter/scope its operations to a specific part of the graph unblocks the workspace improvements & allows for future innovation in this space.

### Exit criteria 

* [ ] `Arborist.loadActual()` supports filtering/scoping by node(s)
* [ ] `Arborist.loadVirtual()` supports filtering/scoping by node(s)
* [ ] `Arborist.buildIdealTree()` supports filtering/scoping by node(s)
* [ ] `Arborist.reify()` supports filtering/scoping by node(s)
* [ ] Tests are written validating this behavior
* [ ] Documentation is updated to identify these methods support this new arg/behavior
