### ISSUE TITLE
feat(workspaces): support `custom` commands

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#274]
### Problem statement

These `npm` commands need to understand where they are to function, read from `package.json` & require **custom** logic.

### Exit criteria 

* [x] All of the following commands will be able to be run with `npm <cmd> -ws`
* [x] Tests are written validating this behavior
* [x] Documentation is updated to identify these command's modified operation when run with `npm -ws` 

**`custom` commands**

* [x] `exec`
* [x] `init`
* [x] `run-script|restart|start|stop|test`
