### ISSUE TITLE
Add monitoring/benchmarking tools

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#3]
- [x] Add a benchmark suite to test against our builds (ex. [pnpm benchmarks](https://github.com/pnpm/benchmarks-of-javascript-package-managers))
- [x] Create a build pipeline/process, separate from the cli builds, to run the benchmarks & generate a report (use GitHub actions if possible)

<details><summary>Requirements</summary>

### Requirements
- [x] Implement `benchmark/` folder with script to run benchmarking commands **[R]**
  - [x] create execution pattern
  - [x] create scenario's paradigm
- [x] Create github action to run benchmark script **[R]**
  - [x] link current commit of repo to global `node_modules/` **[R]**
  - [x] run benchmark script which will run scenarios **[R]**
  - [x] output benchmark results in console **[R]**
- [x] Make output from benchmark run more usable **[R]**
  - [x] write output of scenarios to a `results.yml` file **[R]**
  - [x] write benchmark output to comment in pull-request **[R]**
  - [x] update the same comment in pull-request **[S]**
- [x] Integrate benchmarking run into release process **[R]**
  - [x] write benchmark results to file and commit it **[R]**

##### Legend
**[R]**: required
**[S]**: stretch goal
</details>

<details><summary>Todos</summary>

### TODO:
- [x] update comments in `scenarios.js`[DOCS]
> The information about order is incorrect. The ordering doesn't matter as the result of each run is a full cache, full node_modules, and full lockfile. Each **next** scenario begins with _"everything"_, and must remove the things it doesn't need to complete itself.

- [x] remove `delay` function [CHORE]
> Was used for testing

- [x] Properly comment `index.js` [DOCS]; remove commented code [CHORE]
> Description of what a "scenario" is would be helpful for adding new scenarios in the future. Commented code was a previous iteration and can be removed.

- [x] collect results from each scenario into an object in `index.js`; write this object into a yaml file in `benchmarks/results` [FEAT]
> Currently just writing the results to stdout. We need to keep track of the results for comparison between releases.

- [x] update GitHub Action workflow to only run on pull-request [FIX]
> Currently the workflow runs on `push` which is everything: branches and pull-requests. Need to narrow scope to just pull-requests so that we can be sure to be able to write the results to a comment on said pull-request.

- [x] write "`results.yml`" into a comment on a pull-request [FEAT]
> Using `actions/...@v1` should be able to write a comment for the pull-request this action ran for.

- [x] update release process to include creating "`results.yml`" and committing it to the repository [FEAT]
> A final "`results.yml`" file should be generated at release time, the "released commit" has an idea of it's benchmark.

</details>

<details><summary>Stretch Goal Tasks</summary>

#### Stretch Goal Tasks
- [x] if pull-request comment exists; update said comment
> We want to avoid spamming pull-requests with all the results from each commit pushed to a branch with a pull-request. We should update the same comment; if a comment exists, other write a new comment.

- [x] compare results from current run with those inside `benchmarks/results`
> Need to handle the edge case where that file doesn't exist.

</details>

## Pull-Requests
* https://github.com/npm/package-manager-benchmarks/pull/1 
> pnpm forked repository which has ci update to commit results to repo upon merge into `master` branch

* https://github.com/npm/cli/pull/278
> pull-request to add ci workflow for pull-request events, and pushes to `latest`, `release-next` branches

* https://github.com/npm/benchmarks/pull/1
> pull-request for **benchmarking work** into the `npm/benchmark` repo
