### ISSUE TITLE
Epic: Automated release spike

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#30]
- [ ] Identify a project (not `cli`) to automate the releases of
- [x] Set up CI integration to run tests/benchmarks
- [ ] Set up CD integration to automate versioning/releasing/publishing

**Comment by wraithgar** [comment]
Notes from chats w/ @nlf:

We may want to remove the package-locks from our packages so that our deps PRs don't get unmanageable
If we remove them, we want a scheduled CI for our packages that runs periodically so we know if new deps break our tests.  These can be weekly, nothing egregious.

**Comment by wraithgar** [comment]
With no package-lock audits become tricky.  We can either have an audit action or make npm audit work with no lockfile.

**Comment by darcyclarke** [comment]
### Update
- spike completed
- will be pulling in changes to `template-oss` as a a result of this r&d
