### ISSUE TITLE
Dependency benchmarks spike

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#31]
- [ ] Identify a project (not `cli`) to write a benchmark suite for (ex. [`pacote`](https://github.com/npm/pactoe)) 
- [ ] Set up CI integration to run tests/benchmarks (building off the existing [`benchmarks`](https://github.com/npm/benchmarks) work)
- [ ] Add scenarios for latest yarn/p&p/pnpm to our [`benchmarks`](https://github.com/npm/benchmarks)
