### ISSUE TITLE
Improved Project Observability

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#317]
### Problem statement

Today the CLI team & community has low visibility into the overall project's health creating undue burden/toil to maintain the various OSS projects we depend on.

### Solution

Improve the tooling, automation & visible metrics associated with the projects to help improve supportability

### Resources
- other open source statusboard tool: ref. https://github.com/pkgjs/statusboard
- ex. express org's board https://expressjs.github.io/statusboard/projects

### Exit Criteria
- [x] complete all other dependent features
- [x] add date/time segment selection
    - ie. load multiple data files to accomodate graphs/trends views
    - add selectors for `weekly`, `monthly`, and quarterly (3 month) time frames to show on trendline
    - trendline should update when a selector for time range is selected
- [x] protect against rate limits
    - add strategy for waiting/varying requests
- [x] protect against network failures w/ recovery
    - ie. gracefully fail/fallback
    - ex. retry 3 times w/ exponential backoff
    - might be able to utilize octokit to configure
- [x] add test coverage
    - [x] utilize `node-tap` to write tests
    - [x] 100% initial line coverage for `lib/fetch.js`
- [ ] move Open RFC agenda creation scripts out into `npm/rfcs` repo
- [x] remove any unused/dead code or scripts
- [x] add standard for linting
- [x] add enhancement for deployment status and caching of deployment ids
- [x] make sure ordering is done correctly
- [x] use license value in package.json first, then license from repository data as fallback
- [x] fix `Repository` column on x-axis scroll using https://datatables.net/download/release#FixedHeader
- [x] align `Repository` and `Package` name fields to the left
- [x] add button to toggle all trendline visibility
- [x] implement `sleepover` and iterator for paginated responses due to bug with Octokit and search api throttling.
    - https://github.com/octokit/plugin-throttling.js/issues/109
