### ISSUE TITLE
🐞 Bug Bash (April)

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#336]
- Address [**all** "Needs Triage"](https://github.com/npm/cli/issues?q=is%3Aissue+is%3Aopen+label%3A%22Needs+Triage%22+label%3A%22Release+7.x%22) issues; Checklist:
  - [ ] Ensure bug is reproducible
  - [ ] Respond w/ clarifying questions
  - [ ] Determine & label **Priority** accordingly (no label is required for low-priority icebox/backlogged bugs)
  - [ ] Ensure the ticket is a bug, & not a feature request/enhancement (send those requests to either [feedback](https://github.com/npm/feedback) or [rfcs](https://github.com/npm/feedback))
  - [ ] Close if already resolved, inaccurate or at your discretion
- Address [**all** "Priority 1"](https://github.com/npm/cli/issues?q=is%3Aissue+is%3Aopen+label%3A%22Priority+1%22) bugs
