### ISSUE TITLE
[Web] Clean Up Search Experience

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#34]
- [ ] Remove "powered by npms.io" at bottom of search pages
- [ ] TBD: Fix, change or remove scoring/sorting if the downstream implementation is expected to continue to diverge from [npms.io](https://npms.io)
- [ ] Sync up with @djsauble on the right path forward for the above

**Comment by djsauble** [comment]
We should remove (or at least feature flag) scoring if it's not accurate. But before we do that, I want to know whether it's fixable, and what cost that will incur.

**Comment by darcyclarke** [comment]
Closing this as the responsibility for the website has switched to another team.
