### ISSUE TITLE
Epic: Overrides Support

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#343]
### Problem statement

Users want the ability to override/dependencies as they are being resolved.

### Features
- a user is able to define a set of `overrides` in `package.json` that will resolve dependencies differently at specific points in the tree

### Exit criteria 
- [x] RFC doc is accepted
- [x] feature-set is fully implemented/functioning
  - [x] overrides propagate through tree at load
  - [x] edges are marked invalid if override is not met
  - [x] removing a node removes its overrides
  - [x] adding overrides to a node copies them to all of its edgesOut
  - [x] `nodeFromEdge` in build-ideal-tree takes overrides into account
  - [x] `CanPlaceDep`/`PlaceDep` verify that placing nodes does not violate overrides
- [x] tests are written for coverage of this feature-set
- [x] documentation has been updated for `package.json` (ie. adding a section specifically for `overrides`)

### Useful Links
- [RFC](https://github.com/npm/rfcs/blob/latest/accepted/0036-overrides.md )

**Comment by Haprog** [comment]
I think the RFC link in the description can be updated to https://github.com/npm/rfcs/blob/latest/accepted/0036-overrides.md (as the RFC [PR](https://github.com/npm/rfcs/pull/129) has now been closed and moved to accepted).

**Comment by fernandopasik** [comment]
Any chance this will go any time soon into the https://github.com/npm/roadmap/projects/1 ?

**Comment by darcyclarke** [comment]
For historical reference: https://github.com/npm/statusboard/issues/377

**Comment by Haprog** [comment]
Thanks a lot to everybody involved for making this happen!

**Comment by piotr-cz** [comment]
This is included in npm [v8.3.0 (2021-12-09)](https://github.com/npm/cli/releases/tag/v8.3.0)
