### ISSUE TITLE
Automate Node.js Release PRs

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#349]
### Problem statement

Currently our process for opening a pull requests against the Node.js Project is almost entirely manually done post-release; Letting computers do the work here will save developer time & mindshare as well as reduce complexity or potential for human error.

### Features
- [ ] a GitHub Action kicks off & generates a pull request for `npm` cli releases 
- [ ] the correct staging branch or branches* are targeted (ex. [`v15.x`](https://github.com/nodejs/Release/issues/621), [`v14.x`](https://github.com/nodejs/Release/issues/567), [`v12.x`](https://github.com/nodejs/Release/issues/494) etc. release lines)
- [ ] the correct PR title & description are generated from the changelog (ex. https://github.com/nodejs/node/pulls?q=is%3Apr+is%3Aclosed+npm+label%3Anpm)

### Exit criteria 
- [ ] feature-set fully implemented/functioning
- [ ] release process/documentation is updated
- [ ] Node.js Release WG is made aware of the changes to our process

### Useful Links
- [Release WG](https://github.com/nodejs/release)
- [Our Current Release Process](https://github.com/npm/cli/wiki/Release-Process)
- [Node.js Maintaining `npm` Guide](https://github.com/nodejs/node/blob/master/doc/guides/maintaining-npm.md)
