### ISSUE TITLE
[Web] Improve Analytics Coverage

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#35]
- [ ] Add tracking on package page for outbound clicks (use GA to send events)
- [ ] Add tracking on package page for tab clicks (use GA to send events)
- [ ] Add tracking on search page for sort clicks (use GA to send events)
- [ ] Add tracking for Stripe payment user flow (use GA to set "goals")
- [ ] Add tracking for Email invite user flow (use GA to set "goals")

**Comment by darcyclarke** [comment]
Closing this as the responsibility for the website has switched to another team.
