### ISSUE TITLE
Automate Node.js PR for `npm` Releases

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#356]
### Problem statement

Currently our process for opening a pull requests against the Node.js Project is almost entirely manually done post-release; Letting computers do the work here will save developer time & mindshare as well as reduce complexity or potential for human error.

### Features
- [x] ~a GitHub Action kicks off & generates a pull request for `npm` cli releases~
- [x] a GitHub Action to manually generates a pull request for `npm` cli releases
- [x] targets the correct branch in the upstream `node` repo (ie. `node:master`)
- [x] the correct PR title & description are generated from the release/changelog (ex. https://github.com/nodejs/node/pulls?q=is%3Apr+is%3Aclosed+npm+label%3Anpm)
- [x] should support creating PR's against the correct branches using npm versions (manual overrides are possible w/ GitHub Action inputs)
- [x] the GitHub Action should live inside `npm/cli`

### Exit criteria 
- [x] add @gimli01 to the `npm` team inside the `nodejs/node` project (@darcyclarke)
- [x] ensure a GitHub/npm bot us responsible for the PR created
- [x] release process/documentation is updated
- [x] feature-set fully implemented/functioning
- [x] Node.js Release WG is made aware of the changes to our process

### Useful Links
- [Release WG](https://github.com/nodejs/release)
- [Our Current Release Process](https://github.com/npm/cli/wiki/Release-Process)
- [Node.js Maintaining `npm` Guide](https://github.com/nodejs/node/blob/master/doc/guides/maintaining-npm.md)

### Meeting with @ruyadorno 
- ask for branch mappings from cli to nodejs for support branches
