### ISSUE TITLE
Epic: Dogfood Workspaces

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#362]
### Problem Statement

As a team building a developer tool that is meeting certain needs for monorepo projects, we aren't as aware of the concerns/issues as we don't use the tooling ourselves

### Solution

Start dogfooding workspaces where it makes sense.

### Features

- [x] **Dependency**: [`npm-packlist`](https://github.com/npm/npm-packlist) needs to apply project inclusion rules to bundled linked dependencies
- [x] **Dependency**: [`arborist`](https://github.com/npm/arborist) `reify` & [`@npmcli/map-workspaces`](https://github.com/npm/map-workspaces#readme) must support `root` filter/selector (ex. `.`)
- [x] [introduce new `--workspace=.` root selector to `--workspace` config](https://github.com/npm/statusboard/issues/371)
- [x] make our docs generation a workspace (ie. `/docs`)
- [x] add `libnpmdiff` as a workspace
- [x] add `libnpmfund` as a workspace
- [x] add `libnpmpack` as a workspace
- [x] add `libnpmaccess` as a workspace
- [x] add `libnpmexec` as a workspace
- [x] add `libnpmteam` as a workspace
- [x] add `libnpmsearch` as a workspace
- [x] add `libnpmpublish` as a workspace
- [x] add `libnpmorg` as a workspace
- [x] add `libnpmhook` as a workspace
- [x] add `libnpmversion` as a workspace

### Exit Criteria
- [x] feature-set fully implemented/functioning
- [x] release processes/documentation is updated

**Comment by wraithgar** [comment]
Notes from slack in re packlist: 

> Ah.  That's not quite accurate.
11:37
The semantics of the contract are: if you have a linked dependency, and it's a bundled dependency, we include its files in the tarball as if the link was resolved.
11:38
basically, we just follow the symlink, and treat it otherwise like a normal bundled dep
11:38
so, whatever's there, you obviously said you wanted it there, so we include it
11:39
the change (which I think is reasonable for any bundled+linked dep, not just workspaces) is that we should apply the ignore/include rules along that route when we follow a linked dep, rather than including everything without question like we would for a normal bundled dep

**Comment by darcyclarke** [comment]
### Update
- waiting on `@fritzy` to get back from STO to complete this

**Comment by darcyclarke** [comment]
### Update
- waiting on next release to close out the importing of `lib*` packages

### Actions
- [ ] fix `npm/template-oss` to work for all nested workspace projects
- [ ] need to move any oustanding issues & prs to `npm/cli`
- [ ] archive all old repos
