### ISSUE TITLE
Epic: Output Redesign

### ISSUE THREAD

**Issue by isaacs** [npm/statusboard#366]
Decouple all logging throughout npm modules from `npmlog`, `are-we-there-yet`, and `guage`, while providing an improved user experience and an easier environment in which to iterate on cli output.

SemVer major version of `npmlog` is _solely_ a proc-log consuming display layer module.  (Question: should this maybe instead be a new package name, and deprecate `npmlog`?)

- [x] Every cli module that takes a `log` option should instead use [`proc-log`](http://npm.im/proc-log).  (Temporary exception: Arborist will continue to receive a `log` object so that it can do progress tracking.  Keep reading.)
- [ ] Implement a log/progress event handling display layer based on [`@blessed/neo-blessed`](https://npm.im/@blessed/neo-blessed).
  - [ ] Errors and warnings (anything above the defined loglevel) should be persistent on the screen.
  - [x] All other loglevels _maybe_ we'll want to show, but they should _not_ be persistent if so (silly logs flying by?  is this worthwhile, even?)
  - [x] Create a [`proggy`](http://npm.im/proggy) client to listen on `progress` events, and display progress bars pinned to the bottom of the terminal.
- [x] Replace Arborist's use of npmlog's trackers with proggy loggers.
- [ ] Consider: should progressbars have a loglevel of sorts?  You may want to see a progress bar for _every_ http request if something is hanging, but you probably don't want to normally.
- [x] Replace `cli/lib/doctor.js` use of npmlog trackers with proggy loggers.
- [ ] Remove old npmlog, are we there yet, guage, etc.

Debuglog _file_ management should _not_ be a part of this layer.  See: https://github.com/npm/statusboard/issues/367

**Comment by darcyclarke** [comment]
### Update
- [x] completed primary work associated with this Epic
- [ ] @lukekarrys to create separate issue to track fringe work
