### ISSUE TITLE
Epic: Debug Log File Redesign

### ISSUE THREAD

**Issue by isaacs** [npm/statusboard#367]
Make our handling of debug logs more efficient.

Related to: https://github.com/npm/statusboard/issues/366

- [x] A new module listens on all process `log` events.
- [x] Write all log messages to an append-only file in a known location, with a filename based on the ISO time stamp.
- [x] At the end of the npm cli process, remove any log files in the log folder older than the `npm.config.get('logs-max')` most recent.

This should not be a part of npmlog.  In fact, it can be just a pretty short module in the npm `lib/utils` folder, once everything is using proc-log instead of calling npmlog directly.

**Comment by wraithgar** [comment]
From a slack discussion today:

> for everything that's not arborist moving to proc log today is all benefit w/ no drawback.  We could also consolidate onto proclog in everything except for arborist today for the same reasons.  The last mile is of course the hard one cause we have to solve our progress bar/spinner issue.

**Comment by darcyclarke** [comment]
@lukekarrys can we close this issue out?
