### ISSUE TITLE
feat(pkg): npm pkg get/set/remove

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#368]
### Problem Statement
Developers want an easy & standarized way of getting & modifying the contents of `package.json` through the CLI

### Exit Criteria
- [ ] `npm pkg get` is implemented
- [ ] `npm pkg set` is implemented
- [ ] `npm pkg remove` is implemented
- [ ] Add deprecation warning for `npm set-script`

### Links & Resources
- Reference to the `npm set-script` RFC which should be deprecated by this work: https://github.com/npm/rfcs/blob/latest/implemented/0016-set-script-command.md
- https://www.npmjs.com/package/pkg-jq
