### ISSUE TITLE
[Web] Package Exploration work v2

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#37]
- [ ] Add the ability to route/deeplink into folders/files
- [ ] Add the ability to highlight lines & share that (ex. [github.com/npm/cli/blob/latest/package.json#L17-L19](https://github.com/npm/cli/blob/latest/package.json#L17-L19))
- [ ] Remove paid/gated user condition (ie. fully roll out to all users)
- [ ] Link package.json dependenacies to their corresponding package pages
- [ ] Render markdown files by default
- [ ] Have a rendered vs. raw view for markdown file

**Comment by darcyclarke** [comment]
Closing this as the responsibility for the website has switched to another team.
