### ISSUE TITLE
Epic: Resolve v6 -> v7 regressions

### ISSUE THREAD

**Issue by lukekarrys** [npm/statusboard#397]
In the RFC meeting on [2021-09-22](https://github.com/npm/rfcs/blob/main/meetings/2021-09-22.md#issue-445-%EF%B8%8F-rrfc-breaking-changes-for-npm8---nlf) we discussed tracking/fixing regressions from npm6, and fixing those before npm8.

This is a (so far incomplete) list of those regressions I've found:

- [x] https://github.com/npm/cli/issues/3210
- [x] https://github.com/npm/cli/issues/2740
- [x] https://github.com/npm/cli/issues/3021

**Comment by ljharb** [comment]
We discussed trying to fix them in npm 7, specifically, to ease the upgrade path - ideally they wouldn't have to wait til npm 8.

There's also
 -  https://github.com/npm/cli/issues/2508
 - https://github.com/npm/cli/issues/2610
 - possibly https://github.com/npm/cli/issues/3256
 - possibly https://github.com/npm/cli/issues/3671

**Comment by wraithgar** [comment]
- https://github.com/npm/cli/issues/3530
 - https://github.com/npm/cli/issues/3175

**Comment by wraithgar** [comment]
- https://github.com/npm/cli/issues/3775

**Comment by wraithgar** [comment]
- https://github.com/npm/cli/issues/2606
