### ISSUE TITLE
Epic: Testing

### ISSUE THREAD

**Issue by lukekarrys** [npm/statusboard#410]
### Epic

This epic to to discuss our goals for testing within the cli and how and where we want to pay down tech debt w/r/t testing. Our overarching goal with this should be to test the cli as closely as possible to how it is used in practice. We can also have a sync meeting to go along with this issue for more in depth discussion.

Ideas/spikes/todos:
- [x] ~~Port another command to sandbox to see if any issues come up~~
- [x] Port config test to mockNpm
- [x] Pass argv directly to config to avoid load then config dance we do currently
- [x] Remove last traces of fakenpmmock
- [x] Come up with recipes for more declarative testing. We should provide a way to test more scenarios in a more readable format. I attempted this somewhat with shrinkwrap tests
- [ ] document in testing wiki

**Comment by lukekarrys** [comment]
I created `tap` proposals for features that I think would help us create more declarative and flexible tests:

- https://github.com/tapjs/node-tap/issues/789
- https://github.com/tapjs/node-tap/issues/790
