### ISSUE TITLE
Epic: Linked Install Strategy

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#414]
### Summary
`npm` should be competitive in terms of performance & security as a package manager. Learning from the ecosystem, we can take some of the best ideas introduced by tools, such as `pnpm`, & bring them back into the core experience via configuration (ex. new reification modes).

### Exit Criteria
- [x] create [RFC for shared vs. isolated dependencies]()
- [ ] implement [RFC #42](https://github.com/npm/rfcs/blob/main/accepted/0042-isolated-mode.md)
- [ ] standardize reification modes (ex. `--global-style` & `--legacy-bundling`)
- [x] write test cases
- [x] document feature-set
- [ ] provide benchmarks
- [x] #620
- [ ] #621

**Comment by darcyclarke** [comment]
### Update
- [x] @vincentbailly landed RFC
- [x] @vincentbailly completed initial POC
- [x] @fritzy & @vincentbailly collaborated & completed mapping out phased approach to this work
- @vincentbailly is adding test coverage to help define implementation
- @fritzy is working on platform-level changes to make these changes easier to support/maintain long-term

**Comment by fernandopasik** [comment]
> create [RFC for shared vs. isolated dependencies](https://github.com/npm/statusboard/issues/414)
Is the first point the RFC that was already approved or we are missing a different one? The link points to this same github issue

**Comment by fritzy** [comment]
TODOS:

- [] fix MacOS compatibility
- [] check OS portability
- [] check pack behavior
- [] check updated behavior
- [] fix performance (caching?) cache-only benchmark performance

**Comment by darcyclarke** [comment]
### Update (Oct 31st)
- this work was put on hold as we queued up the v9.0.0 release
- this work is now getting picked up again & should land this quarter
- there is a corresponding open PR with the work at 80-90% completion here: https://github.com/npm/cli/pull/5492

**Comment by darcyclarke** [comment]
### Trending 
🟡 at risk

### Update (Nov 8th)
- @fritzy is OOO this week but will pick up this work when he's back
  - ref. https://github.com/npm/cli/pull/5492
- Competing work (ex. Package Security & build provenance) & significant PTO/STO/OOO (Thanksgiving, Winter Holidays, Vacation etc.) is likely to imped our team's ability - at this point - to properly review & support @fritzy to ship this before end of quarter 
- Flagging this as "at risk" of shipping based on the above

**Comment by darcyclarke** [comment]
### Trending 
🟡 at risk

### Update (Nov 22nd) 
- @fritzy continues to make progress cleaning up the open PR & resolving bugs
- Status of the work remains at risk to finish this quarter given the previous outlined competing priorities & significant OOO
- [ ] @darcyclarke will opening a release issue this week to coordinate this work
- [ ] @darcyclarke / @fritzy to begin drafting a blog post (will engage partners for help there)

**Comment by fritzy** [comment]
### Trending

🟡 at risk

### Update (Dec 5th)
- Work continues on the PR
- Work started on a release blog post
- [ ] start npm CLI team review of PR
- [ ] engage with MS o365 contacts to test on their monorepos
- [ ] write blog post

### Risks
- PTO/OOO time in December for team and contacts

**Comment by fritzy** [comment]
### Trending
🟡 at risk

### Update (Dec 12th)
- Existing PR updated
- Potential initial release this week
- [ ] engage with MS o365 contacts on migrating monorepos
- [ ] write release blog post

**Comment by fritzy** [comment]
### Trending
🟡 at risk / late

### Update (Jan 4th)
- Existing PR updated
- Testing
- [ ] engage with MS o365 contacts on migrating monorepos
- [ ] write release blog post

**Comment by fritzy** [comment]
### Trending
🟡 at risk / late

### Target Date: 18th-Jan-2023

### Update (Jan 10th)
- [x] experiment last week with approach that had less edge cases
- [ ] implement lessons learned from last week
- [ ] release Jan 18th
- [ ] engage with MS o365 contacts on migrating monorepos (today)
- [ ] write release blog post

**Comment by saquibkhan** [comment]
@fritzy As planned are we good for the soft release today?

**Comment by fritzy** [comment]
### Trending
🟡 at risk / late

### Target Date: 25th-Jan-2023

### Update (Jan 18th)
- [x] implement lessons learned from last week (new branch is ready for team review)
- [ ] release Jan 25th (pushed back due to personal illness)
- [x] engaged with MS o365 contacts on migrating monorepos (today)
- [ ] write release blog post (after soft release and feedback)

**Comment by fritzy** [comment]
@saquibkhan I reached out today to Jonathan Creamer at MS to try the new branch (https://github.com/npm/cli/tree/fritzy/linked-install3). My unexpected illness means that the team didn't get a chance to review this new branch, so that's the next step so that we can roll it into the next release.

**Comment by fritzy** [comment]
### Trending
🟢 Launched

### Target Date: 25th-Jan-2023

Worked through bugs and feedback for soft-launch. Now working more with Microsoft to test on their repos, and a blog post to announce.

### Update (Jan 25th)
-  [x] released v9.4.0 `npm install --install-strategy=linked`
- [ ] write release blog post (after soft release and feedback)

**Comment by raiyanalam** [comment]
Closing this issue. Next developments in this area will be tracked here: https://github.com/npm/statusboard/issues/639
cc: @saquibkhan
