### ISSUE TITLE
Epic: Package Selector Syntax

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#415]
### Summary
`npm` should be at the forefront of introducing useful primitives that the ecosystem can use to build more complex tooling & self-serve. Providing a package selector syntax will unlock the ability to ask numerous, complex & unknown questions people have today about their projects & dependencies.

### Exit Criteria
- [ ] create & get accepted an RFC for a new query command & DSL
- [ ] refactor `arborist` to be able to easily walk the graph/tree for this information (ex. migrate to `graphec`)
- [ ] introduce new internal query API & DSL
- [ ] introduce new external query DSL & command (ex. `npm query`)

**Comment by ljharb** [comment]
What is a "package selector syntax"? I have no idea what problem this is solving or what the solution look like. Is there a summary I could read prior to the RFC?

**Comment by darcyclarke** [comment]
I'll share a hackmd doc with you.

**Comment by wraithgar** [comment]
`npm query` shipped in npm 8
