### ISSUE TITLE
npm cli breaking changes

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#488]
This is the issue where we file our future breaking changes for the npm cli.

### Breaking Changes:
1. [ ] Remove legacy lifecycle scripts support (ie. `pre`/`post` scripts)

**Comment by wraithgar** [comment]
Copied from v10 initiative

## v11 and beyond

These are still future looking breaking changes that we want to keep in consideration going forward


```[tasklist]
### Breaking Changes:
- [ ] stop reading process.env.NODE in config for nodeBin
- [ ] remove man pages
- [ ] Remove install scripts support
- [ ] Support for reading `stdin` across **all** commands (ie. https://github.com/npm/rfcs/blob/3d5b2130504139bdc8a3b599923aa07d2ff79c96/accepted/0000-dependency-selector-syntax.md#commands-could-read-from-stdin)
- [ ] Support Package Distributions by default
- [ ] Consider changing strict-ssl default based on environment variables https://github.com/npm/make-fetch-happen/pull/257
```


### Features (v10 or v11 or beyond):

```[tasklist]
- [ ] New `npm link` experience
- [ ] Add new "lifecycle events" API - differentiate between scripts & events - user/project & dependency defined usecases)
- [ ] First-class `import-maps` Support
- [ ] Warn/error on unecessary config items in publishConfig
```

**Comment by ljharb** [comment]
Let's figure out the "store the range i asked for" change for v11 too?

**Comment by wraithgar** [comment]
I just lost an hour of my day to this "clever" helpful line.  We should drop support for this.

https://github.com/npm/cli/blob/1114a12f2b4691d403d0863d4dca44f25580f57d/lib/cli-entry.js#L9-L12

```js
  // if npm is called as "npmg" or "npm_g", then run in global mode.
  if (process.argv[1][process.argv[1].length - 1] === 'g') {
    process.argv.splice(1, 1, 'npm', '-g')
  }
```


```sh
$ node /Users/wraithgar/Development/npm/cli/branches/gar_semver-debug pkg set description='test'
npm ERR! code EPKGGLOBAL
npm ERR! There's no package.json file to manage on global mode
```

**Comment by wraithgar** [comment]
- [ ] Revert all of the hacks around "globstar" in packlist.  Just use node-glob's patterns.

This is just a bug factory at this point.

**Comment by lukekarrys** [comment]
A few things I've found in the issue tracker lately that can't be fixed due to how they would likely break things:

- [ ] Make `--silent` truly silent (eg dont set up any process listeners) and create a net-new way of hiding only logging output. (The opposite could also be done). Then go through and remove all `npm.silent` checks. https://github.com/npm/cli/issues/4877#issuecomment-2109184464
- [ ] Make `run-script` banners a log event. They have been swapped to stderr for json mode, but I think they should always be on stderr. I think an open question would be if they should be called with `output.error` or as an actual log (maybe with a custom `META` prefix)? https://github.com/npm/cli/issues/3354#issuecomment-2108901091
- [ ] Apply `--ignore-scripts` to the `prepare` script when packing and publishing https://github.com/npm/cli/issues/3707

**Comment by wraithgar** [comment]
https://github.com/npm/rfcs/pull/776

**Comment by wraithgar** [comment]
We should remove the npm audit fallback to the old endpoint.  I don't think it works with lockfile v3 anyways.

**Comment by wraithgar** [comment]
Now that hooks is deprecated, and I don't think any other registries support it, it should be removed in npm 11

**Comment by karenjli** [comment]
> Now that hooks is deprecated, and I don't think any other registries support it, it should be removed in npm 11

We will also need to update documentation regarding hooks

**Comment by wraithgar** [comment]
Repurposed this issue as the bucket for all breaking changes.  Actual v11 roadmap is at https://github.com/npm/statusboard/issues/898

**Comment by reggi** [comment]
get rid of "populate deps on init" https://github.com/npm/init-package-json/blob/main/lib/default-input.js#L11-L39

**Comment by reggi** [comment]
get rid of the idea of "package.json as comment in a index file" https://github.com/npm/package-json/blob/main/lib/index.js#L141-L147 😆

**Comment by ljharb** [comment]
@reggi does that last one mean that pre-existing gists might stop being npm-installable?

**Comment by wraithgar** [comment]
@ljharb it's a chesterton's fence issue.  We want to either explain why it's in the road or remove it.  If you have a small gist example that could help us add an explanatory comment in our package-json parser.

**Comment by ljharb** [comment]
Chesterton's fence says to *not* remove it until you *can* explain why it's in the road :-p

https://gist.github.com/isaacs/1837112 is the original canonical example. I'll see if I can find some modern usages.

**Comment by reggi** [comment]
🌶 take  `--workspace={path.basename}` should work if there's only one workspace with that basename

also `--ws=xxx` doesnt throw and really threw me for a loop a couple days back so either awk strings or throw if not boolean

**Comment by wraithgar** [comment]
`bun.lock` is now a thing https://github.com/npm/npm-packlist/pull/257

**Comment by wraithgar** [comment]
https://github.com/npm/statusboard/issues/930
