### ISSUE TITLE
feat(config): Start warning on unknown flags or config  (under `loglevel=warn`)

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#491]
```[tasklist]
### Tasks
- [ ] https://github.com/npm/nopt/pull/179
- [ ] https://github.com/npm/nopt/issues/41
- [ ] https://github.com/npm/statusboard/issues/932
```

**Comment by wraithgar** [comment]
we should also warn when npm is "helpfully" allowing for abbreviated versions of any config item, with the goal of eventual removal in a future major

```sh
$ npm config ls -a -- --bef=2010-10-10|grep before
$ npm config ls -a --bef=2010-10-10|grep before
before = "2010-10-10T00:00:00.000Z"
```

**Comment by wraithgar** [comment]
https://github.com/npm/statusboard/issues/934
