### ISSUE TITLE
Epic: Define Criteria of Acceptable Breaking Changes w/ Node.js

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#574]
### Timeline:
- Collaboration w/ Node.js Release WG: **October-November**
- Document Published: **Wednesday Nov. 9th**

### Goal(s):
- [x] Investigate decoupling npm CLI major updates away from Node.js
- [x] Define & build written agreement with Node.js Release WG about new major versions of `npm`
- [x] @nlf to sync up with `@Trott` on releases/testing/decoupling major `npm` versions from `node` (maybe also get a commit-bit for `nodejs/node` & become an "official" contributor?)

### Links & References
- Scope: https://github.com/nodejs/Release/issues/778#issuecomment-1233445809
- Timeline: https://github.com/nodejs/Release/issues/778#issuecomment-1265458751

**Comment by nlf** [comment]
loose written criteria follows, this will be expanded on in a document that lives elsewhere once we reach consensus with the nodejs team.

1. No new failures in the nodejs project's tests
2. No new failures in citgm
3. No new failures to install package dependencies
4. No unnecessary changes to the package-lock.json, most notably lockfileVersion upgrades must be explicitly requested

**Comment by nlf** [comment]
write up of rules is found here: https://github.com/npm/cli/wiki/Integrating-with-node

i am reaching out to the nodejs team to discuss these rules as well as our testing practices today.

**Comment by nlf** [comment]
the wiki write up is our source of truth for this information. i've shared this info with the nodejs team, who have had nothing but positive feedback. at this point our only remaining work is completing the node integration testing workflow. i'm closing this issue as this criteria has now been defined.
