### ISSUE TITLE
Initiative: Make `v9.x` Generally Available

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#585]
### Summary
Make `npm@9.x` "Generally Available" by setting the `latest` dist-tag & opening a PR with Node.js

### Exit Criteria
- [x] https://github.com/npm/statusboard/issues/574
- [x] On Target Date: Set dist-tags of `latest` to whatever version of `npm@9.x` is most-recent
- [x] On Target Date: PR is open to land `npm@9.x` in `nodejs/node`'s `main` branch

### Links & References
- https://github.com/nodejs/Release/issues/778#issuecomment-1265458751

**Comment by lukekarrys** [comment]
Node PR: https://github.com/nodejs/node/pull/45395
Ref: https://github.com/nodejs/Release/issues/778#issuecomment-1309438189
