### ISSUE TITLE
Initiative: Backport `npm@9.x` in `node@18`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#587]
### Summary
Make `npm@9.x` available in `node@18` after roughly ~6 weeks of `npm@9.x` landing in `node@19` to address any further critical issues (replacing the unmaintained `npm@8.x` version).

### Exit Criteria
- [ ] On Target Date: Open PR to backport `npm@latest` against the `nodejs/node` `v18` branch

### Links & References
- https://github.com/nodejs/Release/issues/778#issuecomment-1265458751

**Comment by nlf** [comment]
we are on track for this target.

our guidelines for integrating with node are written here: https://github.com/npm/cli/wiki/Integrating-with-node

remaining work:

- [ ] Review integration guidelines with nodejs team
- [ ] Review testing practices/demonstrate adherence to guidelines with nodejs team
- [ ] Submit pull request to node 18

**Comment by devinrhode2** [comment]
Previous release notes seem to indicate that node 18 is already supported 🤣

![ScreenShot 2023-04-06 at 14 15 33@2x](https://user-images.githubusercontent.com/539816/230474503-723db3fb-685d-4abf-9aa3-7ac949517dfc.png)

In the blog post for v9, the contradiction appears to be there too:
![ScreenShot 2023-04-06 at 14 17 28@2x](https://user-images.githubusercontent.com/539816/230474612-b9ad8543-be30-429b-8f4e-6719f1e0f191.png)

I'm going to assume that node 18 isn't "officially" supported, so will use npm 8 for now...

**Comment by ljharb** [comment]
Yes, of course node 18 is officially supported - `engines.node` says that - it's just that node 18 doesn't yet *ship* with it.

**Comment by devinrhode2** [comment]
Looks like it is:
<img width="297" alt="ScreenShot 2023-04-06 at 14 33 20@2x" src="https://user-images.githubusercontent.com/539816/230477272-e29822cd-ee7a-4d11-b566-3d94a3579d15.png">

https://github.com/nodejs/Release/issues/778#issuecomment-1472367599
