### ISSUE TITLE
[TRACKING] Release `v8.19.3`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#599]
### Summary
Backporting a few fixes to `v8.x` to resolve some community issues (as `v9.x` will likely not land in `node@lts` for another few months)

### Exit Criteria
- [x] https://github.com/npm/cli/issues/5278
- [x] https://github.com/npm/cli/pull/5761
- [x] https://github.com/npm/cli/pull/5747

**Comment by ljharb** [comment]
What about https://github.com/npm/cli/issues/5777 ?

**Comment by lukekarrys** [comment]
> What about [npm/cli#5777](https://github.com/npm/cli/issues/5777) ?

That probably won't be fixed in time for `8.19.3` tomorrow. Depending on the fix that may be a candidate for a `v8` release but no promises on that yet.
