### ISSUE TITLE
[Initiative] Automated publishing of npm packages from CI/CD

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#625]
### Initiative

One of the last puzzle pieces in our release process is the actual `publish` command.  The eventual goal is publishing to npm from actions alongside all of the other release actions we currently do.

Initial implementation should be opt-in (i.e. repo-level config) driven by template-oss.  OIDC or 2fa will be required.  Human intervention to either kick off or allow the completion of the publish process will also be needed.

```[tasklist]
### Requirements
- [x] Driven by template-oss
- [x] Developer-driven (either to start or continue)
- [x] Access limited to npm-cli team
- [ ] OIDC/2fa required (limited GAT rollout notwithstanding)
- [x] Opt-in per repo (via template-oss config)
```
```[tasklist]
### Phase 1 Q3 FY23
- [ ] #626
- [x] Initial roll out to 5 repos with GAT
- [x] Make decision regarding Deployments
```
```[tasklist]
### Phase 2 Q4 FY23
- [x] Roll out to additional 25 repos with GAT
- [ ] Convert GAT deployments to OIDC (dependent on OIDC launch)
- [ ] ADR for automated publishing of npm/cli
```
```[tasklist]
### Phase 3 Q1 FY24
 - [ ] Roll out for npm/cli
 - [ ] Roll out for remaining non npm/CLI repos
```

We can then move our repos over to this process.

**Comment by saquibkhan** [comment]
OIDC - https://github.com/github/npm/issues/7261
