### ISSUE TITLE
[epic] warn users when altering package.json during publish

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#672]
### Epic

There is a lot of manipulation that read-package-json does when preparing a manifest for publishing. Not all of it can be removed but some if it can (such as typo corrections).  In order to stop doing that in the next semver-major we need to identify which changes we can stop doing, and start warning the user about them now.

A command to apply the fixes needs to also exist to easily clear the warnings.

```[tasklist]
### Tasks
- [x] move read-package-json functionality into `@npmcli/package-json` as-is
- [x] move npm publish to use `@npmcli/package-json`
- [x] identify which changes to warn about
- [x] research if `readme` attribute is load bearing for website
- [x] add discrete `bundleDepencies: false` step to `@npmcli/package-json`
- [x] come up with the mechanism that will warn in 9 and throw in 10
- [ ] add new dev/dependency step to `prepare`
- [x] write `npm pkg fix`
- [x] separate npm's call of `prepare` into warn/don't warn lanes
```

**Comment by wraithgar** [comment]
Decision record for what alterations are going to change in 9/10

## bundledDependencies
npm 9 warns
npm pkg fix fixes
npm 10 throws
## bundleDependencies
- `false`
  - npm 9 warns
  - npm pkg fix fixes (deletes the attribute)
  - npm 10 throws

## gypfile
- npm 9 warns when doing this
- npm 9 warning / 10 exception should direct folks to run `npm pkg set scripts.install="node-gyp rebuild";npm pkg set gypfile=true --json`
- npm 10 errors if `gypfile` is not set to true or false if there is a gypfile present

keep the same logic to show a warning for npm 9 and make it error in npm 10 unless they set `gypfile: true`
action: in normalize change gypfile: true so it sets the correct `install` script
## serverjs
npm 9 warns
npm 10 stops doing this altogether
## scriptpath
- npm 9 warns when doing this
- npm pkg fix fixes this
- npm 10 throws and refuses to accept bad script paths

## authors
We need to discuss this more.  We would like to stop doing this.  Is this a PII issue?
That file is in the tarball already (unless folks ignore it)
## readme
This is not load bearing to the registry or cli.  Is this load bearing for wubwub?
If it is not load bearing for wubwub we should stop doing this.
## binDir
stops normalizing in npm 10 and lets binRefs handle the rest
## normalizeData
lots to unpack here. my goal here would be to convert most things to happening only on the normalize side
also find specific parts that might be loading bearing for publish and make them part of npm pkg fix
# binRefs
- Warn in 9
- npm pkg fix fixes
- Throw in 10
# NEW PREPARE STEP
entries in devDependencies and dependencies that match names
- Warn in 9
- npm pkg fix fixes
- Throw in 10

**Comment by wraithgar** [comment]
This will go out w/ the next npm release.
