### ISSUE TITLE
[epic] npm logging, output, and cleaning

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#810]
### Epic

We are going to consolidate and clean up the code npm uses for output, logging, and for sanitizing strings before doing those things.

Currently these are the modules used:

 - [proc-log](https://github.com/npm/proc-log) (extend)
 - [proggy](https://github.com/npm/proggy) (leave alone for now)
 - [npmlog](https://github.com/npm/npmlog) (deprecate)
 - [gauge](https://github.com/npm/gauge) (deprecate)
 - [are-we-there-yet](https://github.com/npm/are-we-there-yet) (deprecate)
 - [lib/npm.js](https://github.com/npm/cli/blob/1114a12f2b4691d403d0863d4dca44f25580f57d/lib/npm.js#L439-L483)
 - [lib/utils/log-shim.js](https://github.com/npm/cli/blob/latest/lib/utils/log-shim.js) (will go away)
 - [lib/utils/log-file.js](https://github.com/npm/cli/blob/latest/lib/utils/log-file.js)
 - [lib/utils/replace-info.js](https://github.com/npm/cli/blob/latest/lib/utils/replace-info.js) (move to new module)
 - [npm-registry-fetch#cleanUrl](https://github.com/npm/npm-registry-fetch/blob/main/lib/clean-url.js) (move to new module)
 - [lib/utils/display.js](https://github.com/npm/cli/blob/latest/lib/utils/display.js)
 - [lib/utils/error-message.js](https://github.com/npm/cli/blob/latest/lib/utils/error-message.js)
 - [lib/utils/pulse-till-done.js](https://github.com/npm/cli/blob/latest/lib/utils/pulse-till-done.js) (will go away)
 - [lib/utils/reify-output.js](https://github.com/npm/cli/blob/latest/lib/utils/reify-output.js)

This is likely not a comprehensive list, and not everything here belongs in our new consolidated package for npm output concerns.

 ```[tasklist]
### Tasks
- [x] proc-log should have current capabilities moved to sub method .log()
- [x] proc-log should get a method for "standard output"
- [x] proc-log should get a method for "error output" (distinct from log.error)
- [x] replace-info and cleanUrl will be moved to a new package @npmcli/redact
- [x] All of the other functionality will live in npm until proven to need to live elsewhere
- [x] The single console.log in @npmcli/run-script will need to move to the new proc-log standard output method
- [ ] https://github.com/npm/cli/pull/7339
- [ ] https://github.com/npm/proc-log/pull/80
- [ ] https://github.com/npm/proc-log/pull/77
- [ ] https://github.com/npm/cli/pull/7373
- [ ] https://github.com/npm/proc-log/issues/81
- [ ] https://github.com/npm/cli/pull/7377
- [ ] https://github.com/npm/proc-log/pull/85
- [ ] https://github.com/npm/proc-log/pull/84
- [x] https://github.com/npm/cli/blob/latest/lib/utils/format-search-stream.js#L104
- [x] Remove tables (where possible)
- [x] Move https://github.com/npm/disparity-colors to libnpmdiff
- [ ] Remove log "labels"
- [ ] Stop prefixing every log to stdout with `npm ${level}`
- [ ] https://github.com/npm/cli/issues/7354
- [ ] https://github.com/npm/cli/pull/7407
- [ ] https://github.com/npm/cli/pull/7401
```

## Notes

npm progress bars will go away for now

This replaces the following issues
 - https://github.com/npm/statusboard/issues/545
 - https://github.com/npm/statusboard/issues/546
 - https://github.com/npm/statusboard/issues/422

**Comment by lukekarrys** [comment]
Adding `proggy` to the list

**Comment by wraithgar** [comment]
`proggy` does not appear to be used by the latest npm

```sh
~/D/n/c/b/main (latest|✔) $ npm ls proggy
npm@10.5.0 /Users/wraithgar/Development/npm/cli/branches/main
└── (empty)
```

**Comment by lukekarrys** [comment]
### Customizable colors

`npmlog` used to be in charge of colors which we set once at runtime. The `Display` class now generate a color palette on `load` which takes configured options.

Our goal is to have **one** (1) good and accessible color palette for all output shown to the terminal. **BUT** if we find cases where that is impossible (eg dark vs light terminal backgrounds) it is now at least possible to have a config option to change colors.

**Comment by lukekarrys** [comment]
### Command templates

What if a command could do this?

```
// producer
const data = { name, version }
output.standard(data, {
  templates: {
    // pick any templating DSL
    human: `{{ name }}@{{ version }}`,
    parseable: `{{ name }}\t{{ version }}`
  }
})

// consumer
...

```

**Comment by wraithgar** [comment]
Closing this out.  This epic is considered done.  There are follow up tasks that we will put back into the planning queue.  This will all go out w/ the next npm release.
