### ISSUE TITLE
npm v11 Roadmap

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#898]
### Initiative

npm 11

```[tasklist]
### Before release
- [ ] https://github.com/npm/cli/issues/7754
- [ ] https://github.com/npm/statusboard/issues/861
```

```[tasklist]
### For Release (breaking changes)
- [ ] https://github.com/npm/statusboard/issues/899
- [ ] https://github.com/npm/statusboard/issues/901
- [ ] https://github.com/npm/statusboard/issues/900
- [ ] https://github.com/npm/make-fetch-happen/pull/316
- [ ] https://github.com/npm/cli/pull/7808
- [x] make `prepare` obey `--ignore-scripts` config (https://github.com/npm/cli/issues/7211) https://github.com/npm/cli/pull/7850
- [x] remove `npmg` alias detection https://github.com/npm/cli/pull/7842
- [ ] https://github.com/npm/init-package-json/pull/313
- [x] dist-tag safeguards https://github.com/npm/rfcs/pull/776 https://github.com/npm/cli/pull/7939 https://github.com/npm/cli/pull/7910
- [ ] https://github.com/npm/npm-packlist/pull/168
- [x] Make docs site aware of npm 10/11 https://github.com/npm/documentation/pull/1402
- [x] Update sigstore (breaking change due to v3 default)
- [x] release npm 11
```

```[tasklist]
### Post-release
- [ ] Update engines for subdependencies
- [ ] https://github.com/npm/statusboard/issues/913
- [ ] remove and deprecate `read-package-json-fast` https://github.com/npm/statusboard/issues/928
- [x] add npm 11 to Node.js main branch
- [ ] https://github.com/npm/statusboard/issues/931
- [x] rewrite https://github.com/npm/statusboard/issues/488 as a new issue
- [ ] move mocked registry data from arborist to mock-registry
```

**Comment by ljharb** [comment]
It'd be great to include https://github.com/npm/rfcs/pull/547 - there was a PR attempt at one point, but the RFC was misunderstood, and it was abandoned (i can't find it at this time).

**Comment by wraithgar** [comment]
Based on the misunderstandings and issues trying to implement that I think we will not be attempting that one.  This is not a very big release to begin with, mostly cleanup and low hanging fruit.

**Comment by ljharb** [comment]
Ever, or just for v11?

**Comment by wraithgar** [comment]
This is the v11 issue.

**Comment by wraithgar** [comment]
Follow up tasks have issues being tracked. Closing this one
