### ISSUE TITLE
Release v`6.14.5`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#93]
### Dependency Updates
* [x] `mkdirp@0.5.4` ~ meaningful
* [x] `npm-registry-fetch@4.0.4` ~ meaningful
* [x] `graceful-fs@4.2.4` ~ meaningful
* [ ] `gentle-fs@2.3.1` 
* [ ] `libcipm@4.0.8`
* [ ] `bin-links@1.1.8`
* [ ] `npm-lifecycle@3.1.5`
* [ ] `libnpx@10.2.3`
* [ ] `npm-audit-report@1.3.3`
* [x] `nopt@4.0.3` 
* [ ] `safe-buffer@5.1.2`
* [ ] `tar-stream@2.1.0` (devDependency)
* [ ] `uuid@3.3.3`
